image: node:12.18

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - cd cookify_front
    - yarn
    - yarn run build
    - cd ..
    - rm -rf public
    - mv cookify_front/build public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - deploy
